# Jekyll configuration
name: bot_Декарт
description: Bot-Декарт. Каталог статтей з математики

# Url is currently only used only for the RSS feed in feed.xml
url: https://bot-descartes.netlify.com/
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: '/'

author: Bot_Декарт. Каталог статтей з математики
copyright: 2018

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: beregok
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:

permalink: /:year/:month/:title

plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap, jekyll-algolia]

algolia:
  application_id: JW3EBI2XYO
  index_name: bot-descartes
  search_only_api_key: 7153d43fba3a2319ca8ba31f915b9454

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 10

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md']
