# netlify.toml
# This file should be at the root of your project
#  command = "jekyll build && jekyll algolia"
[build]
  command = "jekyll build && jekyll algolia"
  publish = "_site"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=360000"

    for = "/articles/*"
    [headers.values]
      Cache-Control = "public, max-age=360000"
