# netlify.toml
# This file should be at the root of your project
#  command = "jekyll build && jekyll algolia"
[build]
  command = "jekyll build && jekyll algolia"
  publish = "_site"

[[headers]]
  for = "https://bot-descartes.netlify.com/api/articles.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
